theme = "tokyonight"
# theme = "catppuccin_mocha"

[editor]
scrolloff = 13
line-number = "relative"
cursorline = true
color-modes = true
auto-completion = true
auto-format = true
auto-save = true
idle-timeout = 0

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-f = [":new", ":insert-output lf-pick", ":theme default", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":theme tokyonight"]

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
