[battery]
full_symbol = '󰁹 '
charging_symbol = '󰂄 '
discharging_symbol = '󰂃 '
unknown_symbol = '󰂑 '
empty_symbol = '󱊡 '

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
style = "bold red"
charging_symbol = '󰢜 '
discharging_symbol = '󰁺 '

[[battery.display]]  # "bold red" style when capacity is between 10% and 20%
threshold = 20
style = "bold red"
charging_symbol = '󰂆 '
discharging_symbol = '󰁻 '

[[battery.display]]  # "bold yellow" style when capacity is between 20% and 30%
threshold = 30
style = "bold yellow"
charging_symbol = '󰂇 '
discharging_symbol = '󰁼 '

[[battery.display]]  # "bold yellow" style when capacity is between 30% and 40%
threshold = 40
style = "bold yellow"
charging_symbol = '󰂈 '
discharging_symbol = '󰁽 '

[[battery.display]]  # "bold yellow" style when capacity is between 40% and 50%
threshold = 50
style = "bold yellow"
charging_symbol = '󰢝 '
discharging_symbol = '󰁾 '

[[battery.display]]  # "bold green" style when capacity is between 50% and 60%
threshold = 60
style = "bold green"
charging_symbol = '󰂉 '
discharging_symbol = '󰁿 '

[[battery.display]]  # "bold green" style when capacity is between 60% and 70%
threshold = 70
style = "bold green"
charging_symbol = '󰢞 '
discharging_symbol = '󰂀 '

[[battery.display]]  # "bold green" style when capacity is between 70% and 80%
threshold = 80
style = "bold green"
charging_symbol = '󰂊 '
discharging_symbol = '󰂁 '

[[battery.display]]  # "bold green" style when capacity is between 80% and 90%
threshold = 90
style = "bold green"
charging_symbol = '󰂋 '
discharging_symbol = '󰂂 '

[[battery.display]]  # "bold green" style when capacity is between 90% and 100%
threshold = 100
style = "bold green"
charging_symbol = '󰂅 '
discharging_symbol = '󰁹 '

[character]
success_symbol = '[❯](bold green)'
# success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red)'
vicmd_symbol = '[λ](bold green)'

[git_commit]
commit_hash_length = 7
tag_disabled = false
only_detached = false
tag_symbol = '  '

[git_metrics]
disabled = false
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = ""
# home_symbol = "󰶅 "
home_symbol = " "
truncation_length = 13
truncation_symbol = '…/'
# truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Projects" = " "
"go/" = " /"
".config" = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = "⌘ "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
# symbol = " "
# symbol = "󰇷 "
symbol = "󰱵 "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "喝 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰨡 "

[package]
symbol = "󰏖 "

[pijul_channel]
symbol = "🪺 "

[python]
symbol = " "

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[spack]
symbol = "🅢 "
